apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name:  jjinwenflask 
  namespace:  jjinwenflask
  labels: 
    app:  flaskcontainer 
spec: 
  selector: 
    matchLabels: 
      app:  jjinwenflask
  replicas: 1 
  strategy: 
    rollingUpdate: 
      maxSurge: 25% 
      maxUnavailable: 25% 
    type: RollingUpdate 
  template: 
    metadata: 
      labels: 
        app:  flaskcontainer 
    spec: 
      containers: 
      - name:  jjinwenflask 
        image:  jjinwen/flask_app 
        resources: 
          requests: 
            cpu: 100m 
            memory: 100Mi 
          limits: 
            cpu: 100m 
            memory: 100Mi 
        ports: 
        - containerPort:  5000 
          name:  jjinwenflask 
        imagePullPolicy: Always 
      restartPolicy: Always 
 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: jjinwenflask
  namespace: jjinwenflask 
spec: 
  selector: 
    app: flaskcontainer 
  type: LoadBalancer 
  sessionAffinity: None 
  sessionAffinityConfig: 
    clientIP: 
      timeoutSeconds: 10800 
  ports: 
  - name: jjinwenflask 
    protocol: TCP 
    port: 80 
    targetPort: 5000 









